### ISSUE TITLE
PhpDoc()

### ISSUE THREAD

**Issue by jrean** [tobyS/pdv#21]
Hi,
In the source code I can read the following:
```
" You can use this script by mapping the function PhpDoc() to any
" key combination. Hit this on the line where the element to document
" resides and the doc block will be created directly above that line.
```

Where is the PhpDoc() function you are talking about?

For instance the following plugin relies on PDV https://github.com/adoy/vim-php-refactoring-toolbox
```
<Leader>da will call your documentation plugin (by default Php Documentor for vim https://github.com/tobyS/pdv) for every uncommented classes, methods, functions and properties.
```
If I perform the following mapping Vim outputs the following message:

```
PhpDoc() Vim function doesn't exist
```

What do you suggest?

Thank you for the hard work.

**Comment by therealgaxbo** [comment]
I think it's an error in the documentation.  I call DocumentCurrentLine() instead - e.g.:
```
nnoremap <leader>pd :call pdv#DocumentCurrentLine()<CR> 
```

**Comment by jrean** [comment]
Thank you @therealgaxbo.

In the https://github.com/tobyS/pdv/blob/master/autoload/pdv_old.vim there is a function `func! pdv#PhpDoc()` which is not present into the version https://github.com/tobyS/pdv/blob/master/autoload/pdv.vim

Do you confirm there is no function to scan the whole file at a single time that search for missing docBlocks?

:)
