### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cpierce** [tobyS/pdv#28]
Error detected while processing function pdv#DocumentWithSnip[5]..<SNR>177_GenerateDocumentation[2]..<SNR>177_ProcessTemplate:

**Comment by cpierce** [comment]
further info

```
line    1:
E117: Unknown function: vmustache#RenderFile
E15: Invalid expression: vmustache#RenderFile(a:file, a:data)
```

**Comment by cpierce** [comment]
Solved this by installing Plugin 'tobys/vmustache' but it doesn't say anywhere in the docs that this is required.... might update the docs with this info.

**Comment by adriaanzon** [comment]
I think it does. See the requirements section: https://github.com/tobyS/pdv/blob/master/README.rst

**Comment by cpierce** [comment]
ahh see that now.
